/**
 * Ejemplo de Script Ejecutable por SRI Worker
 * 
 * Este es el tipo de script que:
 * 1. Es generado automáticamente por el Control Plane desde steps
 * 2. Es firmado con HMAC-SHA256
 * 3. Es ejecutado por el Worker en sandbox
 * 
 * IMPORTANTE: Este script NO debe ser editado manualmente.
 * Cualquier cambio romperá la firma y será rechazado por el Worker.
 */

// Auto-generated script - DO NOT EDIT MANUALLY
// Generated by SRI Control Plane
// Provider: cargill
// Version: 1.0.0
// Generated at: 2026-01-26T20:00:00.000Z

async function executeFlow(page, context) {
  const results = {};

  // Step 1: navigate
  await page.goto('https://portal.cargill.com/login', { waitUntil: 'networkidle' });

  // Step 2: fill
  await page.fill('#username', context.credentials['username'] || '');

  // Step 3: fill
  await page.fill('#password', context.credentials['password'] || '');

  // Step 4: click
  await page.click('button[type=submit]');

  // Step 5: wait
  await page.waitForSelector('.dashboard', { timeout: 30000 });

  // Step 6: navigate
  await page.goto('https://portal.cargill.com/documents', { waitUntil: 'networkidle' });

  // Step 7: download
  const downloadPromise = page.waitForEvent('download');
  await page.click('.download-ctg');
  const download = await downloadPromise;
  const downloadPath = await download.path();
  results.downloadPath = downloadPath;

  // Step 8: screenshot
  const screenshotPath = 'screenshot_7.png';
  await page.screenshot({ path: screenshotPath, fullPage: true });
  results.screenshot_7 = screenshotPath;

  // Step 9: parse
  // Parser will be applied by worker: cargill-ctg-v1
  results.parser = 'cargill-ctg-v1';

  return results;
}

module.exports = { executeFlow };
