AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SRI Control Plane - Grain Quality System API

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseUrl
        SETTLEMENTS_BUCKET: !Ref SettlementsBucketParam
        NODE_ENV: production

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true
  
  SettlementsBucketParam:
    Type: String
    Description: S3 bucket name for settlements
    Default: sri-settlements-248825820462

Resources:
  # API Gateway (No Auth for now - can add later)
  SriApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SRI Control Plane API
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Tenant-Id'"
        AllowOrigin: "'*'"

  # Lambda Functions
  SettlementsUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-upload
      CodeUri: ../lambdas/settlements-upload/
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref SettlementsBucketParam
      Events:
        UploadSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/upload
            Method: POST

  SettlementsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-list
      CodeUri: ../lambdas/settlements-list/
      Handler: index.handler
      Timeout: 30
      Events:
        ListSettlements:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements
            Method: GET

  SettlementsDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-detail
      CodeUri: ../lambdas/settlements-detail/
      Handler: index.handler
      Events:
        GetSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/{id}
            Method: GET

  SettlementsRecalculateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-recalculate
      CodeUri: ../lambdas/settlements-recalculate/
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      Events:
        RecalculateSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/{id}/recalculate
            Method: POST

  QualityCalculateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-quality-calculate
      CodeUri: ../lambdas/quality-calculate/
      Handler: index.handler
      Events:
        GetQuality:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /ctgs/{ctgNumber}/quality
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${SriApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  
  SettlementsUploadArn:
    Description: ARN of settlements-upload Lambda
    Value: !GetAtt SettlementsUploadFunction.Arn
