AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SRI Control Plane - Grain Quality System API

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseUrl
        SETTLEMENTS_BUCKET: !Ref SettlementsBucket
        NODE_ENV: production
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true
  
  VpcId:
    Type: String
    Description: VPC for Lambda functions
  
  PrivateSubnet1:
    Type: String
    Description: Private subnet 1
  
  PrivateSubnet2:
    Type: String
    Description: Private subnet 2

  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool

Resources:
  # S3 Bucket for PDFs
  SettlementsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sri-settlements-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # Security Group for Lambda
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SRI Lambda functions
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # API Gateway
  SriApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SRI Control Plane API
      StageName: prod
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
          TokenAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: ^Bearer .*$
              ReauthorizeEvery: 0
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Tenant-Id'"
        AllowOrigin: "'*'"

  # Lambda Layer: Prisma Client
  PrismaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: prisma-client
      Description: Prisma Client for PostgreSQL
      ContentUri: ../layers/prisma-layer/
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

  # Lambda Functions
  SettlementsUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-upload
      CodeUri: ../lambdas/settlements-upload/
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Sub 'sri-settlements-${AWS::AccountId}'

      Events:
        UploadSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/upload
            Method: POST

  SettlementsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-list
      CodeUri: ../lambdas/settlements-list/
      Handler: index.handler
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole

      Events:
        ListSettlements:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements
            Method: GET

  SettlementsDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-detail
      CodeUri: ../lambdas/settlements-detail/
      Handler: index.handler
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole

      Events:
        GetSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/{id}
            Method: GET

  SettlementsRecalculateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-settlements-recalculate
      CodeUri: ../lambdas/settlements-recalculate/
      Handler: index.handler
      Timeout: 300
      MemorySize: 1024
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole

      Events:
        RecalculateSettlement:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /settlements/{id}/recalculate
            Method: POST

  QualityCalculateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-quality-calculate
      CodeUri: ../lambdas/quality-calculate/
      Handler: index.handler
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole

      Events:
        GetQuality:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /ctgs/{ctgNumber}/quality
            Method: GET

  DocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-documents-handler
      CodeUri: ../lambdas/documents-handler/
      Handler: index.handler
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Sub 'sri-settlements-${AWS::AccountId}'

      Events:
        ListDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /documents
            Method: GET
        UploadDocument:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /documents/upload
            Method: POST

  StocksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-stocks-handler
      CodeUri: ../lambdas/stocks-handler/
      Handler: index.handler
      Layers:
        - !Ref PrismaLayer
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole

      Events:
        ListStocks:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /stocks
            Method: GET
        UpdateStocks:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /stocks
            Method: POST

  ProvidersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-providers-handler
      CodeUri: ../lambdas/providers-handler/
      Handler: index.handler
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole
      Events:
        ListProviders:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /providers/list
            Method: GET
        ConnectProvider:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /providers/connect
            Method: POST
        ForceConnectProvider:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /providers/force-connect
            Method: POST
        DisconnectProvider:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /providers/delete/{id}
            Method: DELETE

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-auth-handler
      CodeUri: ../lambdas/auth-handler/
      Handler: index.handler
      Environment:
        Variables:
          JWT_SECRET: sri-secret-key-2026-prod-v2
          DB_NAME: sri_production
      Policies:
        - VPCAccessPolicy: {}
        - AWSLambdaBasicExecutionRole
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /auth/login
            Method: POST
            Auth:
              Authorizer: NONE
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref SriApi
            Path: /auth/register
            Method: POST
            Auth:
              Authorizer: NONE

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sri-token-authorizer
      CodeUri: ../lambdas/authorizer/
      Handler: index.handler
      Environment:
        Variables:
          JWT_SECRET: sri-secret-key-2026-prod-v2

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${SriApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  
  SettlementsBucketName:
    Description: S3 bucket for settlement PDFs
    Value: !Ref SettlementsBucket
  
  SettlementsUploadArn:
    Description: ARN of settlements-upload Lambda
    Value: !GetAtt SettlementsUploadFunction.Arn
